In [1]:
import numpy as np, cv2

In [17]:
image1 = cv2.imread('003.jpg')
image2 = cv2.imread('004.jpg')
image1.shape, image2.shape
 
(h,w),(H,W) =     image1.shape[:2], image2.shape[:2]
minH = np.min((h,H))
minW = np.min((w,W))
image1 = image1[:minH,:minW]
image2 = image2[:minH,:minW]    
image1.shape,  image2.shape

((183, 199, 3), (183, 199, 3))

In [18]:
# 곱셈의 비율
alpha, beta = 0.6,0.7
add_image1 =  cv2.add(image1,image2)
add_image2 =  cv2.add(image1*alpha,image2*beta)
add_image2 = np.clip(add_image2,0,255).astype('uint8')
add_image3 = cv2.addWeighted(image1,alpha,image2,beta,0)  #두 영상 비율에 따라 더하기

titles = ['image1','image2','add_image1','add_image2','add_image3']
for title in titles:
    cv2.imshow(title,eval(title))
cv2.waitKey(0)
cv2.destroyAllWindows()

In [4]:
image1*alpha

array([[132. , 132. , 132. , ..., 129. , 129. , 129. ],
       [132. , 132. , 132. , ..., 129. , 129. , 129. ],
       [132. , 132. , 132. , ..., 128.4, 128.4, 128.4],
       ...,
       [100.8, 101.4, 101.4, ..., 116.4, 115.8, 115.8],
       [102. , 101.4, 102. , ..., 114. , 114. , 113.4],
       [102.6, 101.4, 102.6, ..., 112.2, 112.2, 112.2]])

In [5]:
image1

array([[220, 220, 220, ..., 215, 215, 215],
       [220, 220, 220, ..., 215, 215, 215],
       [220, 220, 220, ..., 214, 214, 214],
       ...,
       [168, 169, 169, ..., 194, 193, 193],
       [170, 169, 170, ..., 190, 190, 189],
       [171, 169, 171, ..., 187, 187, 187]], dtype=uint8)

In [6]:
add_image2

array([[209. , 217.4, 214.6, ..., 244.5, 245.2, 245.2],
       [232.1, 243.3, 249.6, ..., 244.5, 245.2, 245.2],
       [212.5, 213.9, 230. , ..., 243.9, 244.6, 244.6],
       ...,
       [123.2, 130.1, 132.9, ..., 140.2, 138.2, 136.8],
       [120.9, 125.9, 130. , ..., 191. , 190.3, 189. ],
       [131.3, 126.6, 124.3, ..., 214.4, 215.8, 216.5]])