In [45]:
import numpy as np, cv2

In [46]:
image1 = cv2.imread('./abs_test1.jpg')#, cv2.IMREAD_GRAYSCALE)  # 명암도 영상 읽기
image2 = cv2.imread('./abs_test2.jpg')#, cv2.IMREAD_GRAYSCALE)  # 명암도 영상 읽기

In [47]:
image1.shape, image2.shape
dif_img1 = cv2.subtract(image1,image2)
dif_img2 = cv2.subtract(np.int16(image1), np.int16(image2))
abs_dif1 = np.absolute(dif_img2).astype('uint8')
abs_dif2 = cv2.absdiff(image1,image2)

In [48]:
# 관심영역 roi
x,y,w,h = 100,150,7,3
print(dif_img1[y:y+h, x:x+w])
print(dif_img2[y:y+h, x:x+w])
print(abs_dif1[y:y+h, x:x+w])
print(abs_dif2[y:y+h, x:x+w])

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[ 12288  17152  22784]
  [  9728  14592  20480]
  [ 10496  15360  20992]
  [ 10240  15104  20736]
  [  8192  12800  18688]
  [ 14592  19200  24576]
  [ 25600  30720 -30464]]

 [[ 10240  15104  20736]
  [  9472  14336  20224]
  [ 11008  15872  21504]
  [  9984  14848  20480]
  [  8960  13568  19456]
  [ 13056  17664  23040]
  [ 28416 -32000 -27648]]

 [[ 10496  14080  21248]
  [ 10752  14336  21504]
  [ 11520  15104  22272]
  [ 12288  15872  23040]
  [ 13568  18176  26112]
  [  8192  13056  20480]
  [ 19456  24576  30976]]]
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[208 189 167]
  [218 199 176]
  [21

In [49]:
images = [image1,image2,dif_img1,dif_img2,abs_dif1,abs_dif2]
for idx, image in enumerate(images):
    cv2.imshow(str(idx+1),image)
cv2.waitKey(0)    
cv2.destroyAllWindows()