In [1]:
# 신경망 2층짜리
from tensorflow import keras
from tensorflow.keras import layers

In [2]:
# 원시데이터 사용
from tensorflow.keras.datasets import mnist
(x_train,y_train),(x_test,y_test)  = mnist.load_data()
x_train = x_train.reshape(-1,28*28)
x_test = x_test.reshape(-1,28*28)
x_train.shape
model = keras.Sequential(
    [
        layers.Dense(512, activation='relu'),
        layers.Dense(10,activation='softmax')
    ]
)
# 컴파일
model.compile(optimizer='adam',loss=keras.losses.sparse_categorical_crossentropy,metrics=['accuracy'])
# model.fit( x_train  ,y_train, epochs=1, validation_data=(x_test,y_test) )

In [3]:
# 데이터를 정규화
# 원시데이터 사용
from tensorflow.keras.datasets import mnist
(x_train,y_train),(x_test,y_test)  = mnist.load_data()
x_train = x_train.reshape(-1,28*28)
x_test = x_test.reshape(-1,28*28)

x_train = x_train.astype('float32') / 255
x_test = x_test.astype('float32') / 255

x_train.shape
model = keras.Sequential(
    [
        layers.Dense(512, activation='relu'),
        layers.Dense(10,activation='softmax')
    ]
)
# 컴파일
model.compile(optimizer='adam',loss=keras.losses.sparse_categorical_crossentropy,metrics=['accuracy'])
# model.fit( x_train  ,y_train, epochs=1, validation_data=(x_test,y_test) )

In [4]:
# 모델 예측

# 모델 평가


In [5]:
# 스칼라(랭크-0 텐서)
import numpy as np
x = np.array(12)
x, x.ndim


(array(12), 0)

In [6]:
# 벡터(랭크-1 텐서)
x = np.array([12])
x, x.ndim

(array([12]), 1)

In [7]:
# 행렬(랭크-2 텐서)
x = np.array([[12]])
x, x.ndim

(array([[12]]), 2)

In [8]:
# 랭크 -3 및 over
x = np.array([[[12]]])
x, x.ndim

(array([[[12]]]), 3)

In [9]:
(x_train,y_train),(x_test,y_test)  = mnist.load_data()
x_train.ndim

3

In [10]:
x_train[10:100].shape

(90, 28, 28)

In [11]:
x_train[10:100,:,:].shape

(90, 28, 28)

In [12]:
x_train[10:100,:20,:20].shape

(90, 20, 20)

In [13]:
batch = x_train[:128]
batch = x_train[128:128+128]

In [14]:
x = np.random.randn(20,100)
y = np.random.randn(20,100)

In [15]:
# np.maximum(x,0)
def native_relu(x):
    assert len(x.shape) == 2
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i,j] = max(x[i,j],0)
    return x

In [16]:
native_relu(x)

array([[0.01718302, 0.        , 0.        , ..., 0.        , 0.66269332,
        0.24017385],
       [0.        , 0.87785409, 0.        , ..., 0.        , 0.        ,
        1.12314513],
       [0.82997862, 0.        , 0.        , ..., 0.32736159, 0.        ,
        1.25947017],
       ...,
       [0.99607025, 0.88681071, 0.40293322, ..., 0.        , 0.94855066,
        0.        ],
       [0.42211791, 0.        , 0.17607395, ..., 0.49440191, 0.21661307,
        1.15843805],
       [0.        , 0.54966289, 1.78162468, ..., 0.        , 0.19618036,
        1.51671273]])

In [17]:
# 텐서의 add 연산  넘파이의 add 연산
def native_add(x,y):
    assert len(x.shape) == 2
    assert x.shape == y.shape
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i,j] += y[i,j]
    return x

In [18]:
native_add(x,y)

array([[ 1.56026059, -0.53436789, -0.03059656, ...,  0.20996294,
         0.84495868, -1.36562322],
       [ 0.06628283,  1.33805169,  0.31232847, ...,  0.61091939,
        -0.29476174,  1.34826559],
       [ 1.58719618, -1.88013027,  0.4732785 , ...,  0.89053692,
         0.61633528,  0.14959928],
       ...,
       [ 1.53903326,  0.69757476,  1.53354658, ..., -0.53311754,
         1.06419105,  0.91836028],
       [ 2.33381763, -2.50901818, -0.10535542, ...,  3.35610051,
        -0.91554392,  0.9213467 ],
       [ 1.6106614 ,  0.12641029,  2.42742324, ..., -2.0708805 ,
         0.02304044,  2.53669749]])

In [19]:
import time
start = time.time()
for _ in range(1000):
    z = x + y
    z = np.maximum(z,0)
time.time() - start    

0.006982088088989258

In [20]:
import time
start = time.time()
for _ in range(1000):
    z = native_add(x,y)
    z = native_relu(z)
time.time() - start    

1.5901000499725342

In [21]:
import numpy as np
x = np.random.random((32,10))
y =  np.random.random((10,))
y.shape

(10,)

In [22]:
np.expand_dims(y, axis=0).shape, np.expand_dims(y, axis=1).shape


((1, 10), (10, 1))

In [23]:
y = np.expand_dims(y, axis=0)

In [24]:
np.concatenate([y]*32, axis=0)

array([[0.12972858, 0.97023698, 0.29970896, 0.83772203, 0.48936407,
        0.33555506, 0.92830793, 0.87860763, 0.4179273 , 0.77210003],
       [0.12972858, 0.97023698, 0.29970896, 0.83772203, 0.48936407,
        0.33555506, 0.92830793, 0.87860763, 0.4179273 , 0.77210003],
       [0.12972858, 0.97023698, 0.29970896, 0.83772203, 0.48936407,
        0.33555506, 0.92830793, 0.87860763, 0.4179273 , 0.77210003],
       [0.12972858, 0.97023698, 0.29970896, 0.83772203, 0.48936407,
        0.33555506, 0.92830793, 0.87860763, 0.4179273 , 0.77210003],
       [0.12972858, 0.97023698, 0.29970896, 0.83772203, 0.48936407,
        0.33555506, 0.92830793, 0.87860763, 0.4179273 , 0.77210003],
       [0.12972858, 0.97023698, 0.29970896, 0.83772203, 0.48936407,
        0.33555506, 0.92830793, 0.87860763, 0.4179273 , 0.77210003],
       [0.12972858, 0.97023698, 0.29970896, 0.83772203, 0.48936407,
        0.33555506, 0.92830793, 0.87860763, 0.4179273 , 0.77210003],
       [0.12972858, 0.97023698, 0.2997089

In [25]:
x = np.random.random((5))
y = np.random.random((5))
x,y,x.shape, y.shape

(array([0.5163083 , 0.18749233, 0.74266738, 0.6591433 , 0.05756919]),
 array([0.93263895, 0.89655453, 0.00178882, 0.88046492, 0.08077703]),
 (5,),
 (5,))

In [26]:
z = np.dot(x,y)
z

1.2359576384314517

In [27]:
def native_vector_dot(x,y):
    assert len(x.shape) == 1
    assert len(y.shape) == 1
    assert y.shape[0] == x.shape[0]
    z = 0
    for i in range(x.shape[0]):    
        z += x[i] * y[i]
    return z

In [28]:
x = np.random.random((2,2))
y = np.random.random((2))
x,y,x.shape, y.shape

(array([[0.30917402, 0.78863087],
        [0.28533182, 0.03278106]]),
 array([0.93816602, 0.46607669]),
 (2, 2),
 (2,))

In [29]:
np.dot(x,y)

array([0.65761903, 0.28296711])

In [30]:
def native_matrix_vector_dot(x,y):
    assert len(x.shape) == 2
    assert len(y.shape) == 1
    assert x.shape[1] == y.shape[0]
    z = np.zeros(x.shape[0])
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            z[i] += x[i,j] * y[j]
    return z

In [31]:
def native_matrix_vector_dot(x,y):    
    z = np.zeros(x.shape[0])
    for i in range(x.shape[0]):        
        z[i]  = native_vector_dot(x[i, :], y)
    return z

In [32]:
# native_vector_dot 을 이용해서 작성
def native_matrix_dot(x,y):
    assert len(x.shape) == 2
    assert len(y.shape) == 2
    assert x.shape[1] == y.shape[0]
    

In [33]:
x = np.zeros((32,20))
print(x.shape)
xt = np.transpose(x)
xt.shape


(32, 20)


(20, 32)

In [34]:
x = np.array([[1,2],[3,4],[5,6]])
x = np.expand_dims(x, axis=-1)
x.shape , x

((3, 2, 1),
 array([[[1],
         [2]],
 
        [[3],
         [4]],
 
        [[5],
         [6]]]))

In [35]:
x.T, x.T.shape

(array([[[1, 3, 5],
         [2, 4, 6]]]),
 (1, 2, 3))

In [36]:
x.transpose(1,2,0), x.transpose(1,2,0).shape

(array([[[1, 3, 5]],
 
        [[2, 4, 6]]]),
 (2, 1, 3))

In [37]:
# 자동미분
import tensorflow as tf
x = tf.Variable(0.)
with tf.GradientTape() as tape:
    y = 2*x + 3
grad_y = tape.gradient(y,x)    

In [38]:
w = tf.Variable(tf.random.uniform((2,2)))
b = tf.Variable(tf.zeros((2,)))
x = tf.random.uniform((2,2))
with tf.GradientTape() as tape:
    y = tf.matmul(x,w) +b

grade_y = tape.gradient(y, [w,b])
                

In [39]:
grade_y

[<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[1.4641707 , 1.4641707 ],
        [0.67615736, 0.67615736]], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([2., 2.], dtype=float32)>]

In [40]:
class NativeDense:
    def __init__(self, input_size, output_size, activation):
        self.activation = activation
        w_shape = (input_size, output_size)
        w_init_value = tf.random.uniform(w_shape,  minval=0, maxval=1e-1)
        self.W = tf.Variable(w_init_value)
        
        b_shape = (output_size,)
        b_init_value = tf.zeros(b_shape)
        self.b = tf.Variable(b_init_value)
    def __call__(self, inputs):        
        return self.activation(tf.matmul(inputs,self.W) + self.b)
    @property
    def weights(self):
        return [self.W, self.b]

In [41]:
class Dumy:
    def __init__(self):
        print("객체가 생성되었습니다.")
    def __call__(self, data):
        return f"전달된 데이터는 {data}"
    @property
    def abc(self):
        return 1000
    

In [42]:
d = Dumy()

객체가 생성되었습니다.


In [43]:
d("우헤헤"), d.abc

('전달된 데이터는 우헤헤', 1000)

In [44]:
class NativeSequential:
    def __init__(self,layers):
        self.layers = layers
    def __call__(self, inputs):
        x = inputs
        for layer in self.layers:
            x = layer(x)
        return x   
    @property
    def weights(self):
        weights = []
        for layer in self.layers:
            weights += layer.weights
        return weights

In [45]:
model = NativeSequential(
    [
        NativeDense(input_size=28*28,output_size=128,activation=tf.nn.relu),
        NativeDense(input_size=128,output_size=10,activation=tf.nn.softmax),
    ]
)
assert len(model.weights) == 4

In [46]:
# 배치 제너레이터
import math
class BatchGenerator:
    def __init__(self, images, labels, batch_size = 128):
        assert len(images) == len(labels)
        self.index = 0
        self.images = images
        self.labels = labels
        self.batch_size = batch_size
        self.num_batchs = math.ceil(len(images) / batch_size)
    def next(self):
        images = self.images[self.index: self.index + self.batch_size]
        labels = self.labels[self.index: self.index + self.batch_size]
        self.index += self.batch_size
        return images, labels

In [47]:
learning_rate = 1e-2
# def update_weights(gradients, weights):
#     for g,w in zip(gradients, weights):
#         w.assign_sub(g*learning_rate)

In [48]:
from tensorflow.keras import optimizers
optimizer = optimizers.SGD(learning_rate=learning_rate)
def update_weights(gradient, weights):
    optimizer.apply_gradients(zip(gradient, weights))

In [49]:
# 훈련스텝
def one_training_step(model, images_batch, labels_batch):
    with tf.GradientTape() as tape:
        predictions = model(images_batch)        
        loss = tf.keras.losses.sparse_categorical_crossentropy(labels_batch,predictions)
        average_loss =  tf.reduce_mean(loss)
    gradients = tape.gradient(average_loss, model.weights)
    # 업데이트
    update_weights(gradients,model.weights)
    return average_loss

In [50]:
# 객제지향 프로그램에서 변수
def AA():
    pass
BB = 10
AA, BB

(<function __main__.AA()>, 10)

In [51]:
# 전체 훈련 loop 설계
from tqdm import tqdm
def fit(model, images, labels, epochs, batch_size = 32):
    for epoch in tqdm(range(epochs)):
        print(f"epoch : {epoch}") 
        batch_generator = BatchGenerator(images, labels)
        for batch in range(batch_generator.num_batchs):
            images_batch, labels_batch =  batch_generator.next()
            loss = one_training_step(model, images_batch, labels_batch)
            if batch % 100 ==0:
                print(f"{batch} loss : {loss:.2f}")
        

In [52]:
from tensorflow.keras.datasets import mnist
(x_train,y_train),(x_test,y_test) = mnist.load_data()
x_train = x_train.reshape(-1,28*28)
x_test = x_test.reshape(-1,28*28)

x_train = x_train.astype('float32') / 255.
x_test = x_test.astype('float32') / 255.


In [53]:
x_train.shape

(60000, 784)

In [54]:
fit(model,x_train,y_train,epochs=10,batch_size=100)

  0%|                                                                                                                    | 0/10 [00:00<?, ?it/s]

epoch : 0
0 loss : 3.92
100 loss : 4.46
200 loss : 4.59
300 loss : 3.55
400 loss : 2.19


 10%|██████████▊                                                                                                 | 1/10 [00:03<00:27,  3.02s/it]

epoch : 1
0 loss : 2.53
100 loss : 1.51
200 loss : 1.15
300 loss : 0.63
400 loss : 0.70


 20%|█████████████████████▌                                                                                      | 2/10 [00:05<00:22,  2.82s/it]

epoch : 2
0 loss : 0.59
100 loss : 0.56
200 loss : 0.52
300 loss : 0.47
400 loss : 0.55


 30%|████████████████████████████████▍                                                                           | 3/10 [00:07<00:17,  2.49s/it]

epoch : 3
0 loss : 0.46
100 loss : 0.42
200 loss : 0.35
300 loss : 0.41
400 loss : 0.50


 40%|███████████████████████████████████████████▏                                                                | 4/10 [00:10<00:14,  2.45s/it]

epoch : 4
0 loss : 0.40
100 loss : 0.36
200 loss : 0.30
300 loss : 0.38
400 loss : 0.48


 50%|██████████████████████████████████████████████████████                                                      | 5/10 [00:12<00:11,  2.37s/it]

epoch : 5
0 loss : 0.36
100 loss : 0.32
200 loss : 0.28
300 loss : 0.36
400 loss : 0.46


 60%|████████████████████████████████████████████████████████████████▊                                           | 6/10 [00:14<00:09,  2.27s/it]

epoch : 6
0 loss : 0.33
100 loss : 0.30
200 loss : 0.26
300 loss : 0.34
400 loss : 0.45


 70%|███████████████████████████████████████████████████████████████████████████▌                                | 7/10 [00:16<00:06,  2.28s/it]

epoch : 7
0 loss : 0.31
100 loss : 0.28
200 loss : 0.25
300 loss : 0.33
400 loss : 0.44


 80%|██████████████████████████████████████████████████████████████████████████████████████▍                     | 8/10 [00:19<00:04,  2.35s/it]

epoch : 8
0 loss : 0.29
100 loss : 0.27
200 loss : 0.24
300 loss : 0.32
400 loss : 0.44


 90%|█████████████████████████████████████████████████████████████████████████████████████████████████▏          | 9/10 [00:21<00:02,  2.29s/it]

epoch : 9
0 loss : 0.27
100 loss : 0.25
200 loss : 0.23
300 loss : 0.32
400 loss : 0.43


100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:23<00:00,  2.37s/it]


In [57]:
# 모델 평가
predictions = model(x_test)

In [62]:
(predictions.numpy().argmax(1) == y_test).mean()

0.9021

In [ ]:
# 훈련과정을. 시각화