In [1]:
# 로지스틱회귀 분석 - 유방암 진단
# 결정트리 분석 + 산점도/선형회귀 그래프 - 센서데이터로 움직임 분류

In [2]:
# 로지스틱회귀 - 이진 분류
# 로지스틱회귀 - 질병 진단
# 결정트리 - 다중분류
# 결정트리를 이용해서 움직임을 분류

In [3]:
# 로지스틱회귀 - 유방암데이터를 이용해서 유방암 발생을 예측
# 로지스틱 회귀  -시그모이드 함수를 이용
# - 분류에 사용하는 기법 S자함수를 사용해서 참과 거짓을 분류
# 오차행렬.. 혼동행렬 Confusion Matrix
# 평가지표는 오차행렬을 이용해서 accuracy인 정확도를 측정
# 사이킷런에서 score 함수를 제공.-- accuracy

In [4]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [5]:
from sklearn.datasets import load_breast_cancer

In [6]:
b_cancer = load_breast_cancer()

In [9]:
df = pd.DataFrame(data=b_cancer.data, columns=b_cancer.feature_names)
df.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst radius  worst texture  worst perimeter  \
0                 0.07871  ...         25.38          17.33           184.60   
1                 0.05667  ...         24.99          23.41           158.80   
2                 0.05999  ...         23.57          25.53           152.50   
3                 0.09744  ...         14.91          26.50            98.87   
4                 0.05883  ...         22.54          16.67           152.20   

   worst area  worst smoothness  worst compactness  worst concavity  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   worst concave points  worst symmetry  worst fractal dimension  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 30 columns]

In [12]:
df['class'] = b_cancer.target
df.head(1)

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38           122.8     1001.0           0.1184   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0            0.2776          0.3001               0.1471         0.2419   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                 0.07871  ...          17.33            184.6      2019.0   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1622             0.6656           0.7119                0.2654   

   worst symmetry  worst fractal dimension  class  
0          0.4601                   0.1189      0  

[1 rows x 31 columns]

In [15]:
df.shape  # class 1이면 악성   0이면 양성

(569, 31)

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   mean radius              569 non-null    float64
 1   mean texture             569 non-null    float64
 2   mean perimeter           569 non-null    float64
 3   mean area                569 non-null    float64
 4   mean smoothness          569 non-null    float64
 5   mean compactness         569 non-null    float64
 6   mean concavity           569 non-null    float64
 7   mean concave points      569 non-null    float64
 8   mean symmetry            569 non-null    float64
 9   mean fractal dimension   569 non-null    float64
 10  radius error             569 non-null    float64
 11  texture error            569 non-null    float64
 12  perimeter error          569 non-null    float64
 13  area error               569 non-null    float64
 14  smoothness error         5

In [17]:
df.describe()

mean radius  mean texture  mean perimeter    mean area  \
count   569.000000    569.000000      569.000000   569.000000   
mean     14.127292     19.289649       91.969033   654.889104   
std       3.524049      4.301036       24.298981   351.914129   
min       6.981000      9.710000       43.790000   143.500000   
25%      11.700000     16.170000       75.170000   420.300000   
50%      13.370000     18.840000       86.240000   551.100000   
75%      15.780000     21.800000      104.100000   782.700000   
max      28.110000     39.280000      188.500000  2501.000000   

       mean smoothness  mean compactness  mean concavity  mean concave points  \
count       569.000000        569.000000      569.000000           569.000000   
mean          0.096360          0.104341        0.088799             0.048919   
std           0.014064          0.052813        0.079720             0.038803   
min           0.052630          0.019380        0.000000             0.000000   
25%           0.086370          0.064920        0.029560             0.020310   
50%           0.095870          0.092630        0.061540             0.033500   
75%           0.105300          0.130400        0.130700             0.074000   
max           0.163400          0.345400        0.426800             0.201200   

       mean symmetry  mean fractal dimension  ...  worst texture  \
count     569.000000              569.000000  ...     569.000000   
mean        0.181162                0.062798  ...      25.677223   
std         0.027414                0.007060  ...       6.146258   
min         0.106000                0.049960  ...      12.020000   
25%         0.161900                0.057700  ...      21.080000   
50%         0.179200                0.061540  ...      25.410000   
75%         0.195700                0.066120  ...      29.720000   
max         0.304000                0.097440  ...      49.540000   

       worst perimeter   worst area  worst smoothness  worst compactness  \
count       569.000000   569.000000        569.000000         569.000000   
mean        107.261213   880.583128          0.132369           0.254265   
std          33.602542   569.356993          0.022832           0.157336   
min          50.410000   185.200000          0.071170           0.027290   
25%          84.110000   515.300000          0.116600           0.147200   
50%          97.660000   686.500000          0.131300           0.211900   
75%         125.400000  1084.000000          0.146000           0.339100   
max         251.200000  4254.000000          0.222600           1.058000   

       worst concavity  worst concave points  worst symmetry  \
count       569.000000            569.000000      569.000000   
mean          0.272188              0.114606        0.290076   
std           0.208624              0.065732        0.061867   
min           0.000000              0.000000        0.156500   
25%           0.114500              0.064930        0.250400   
50%           0.226700              0.099930        0.282200   
75%           0.382900              0.161400        0.317900   
max           1.252000              0.291000        0.663800   

       worst fractal dimension       class  
count               569.000000  569.000000  
mean                  0.083946    0.627417  
std                   0.018061    0.483918  
min                   0.055040    0.000000  
25%                   0.071460    0.000000  
50%                   0.080040    1.000000  
75%                   0.092080    1.000000  
max                   0.207500    1.000000  

[8 rows x 31 columns]

In [140]:
# 데이터의 범위를 표준화
# 평균0 ~ 분산이1 되는 정규분포 형태로
from sklearn.preprocessing import StandardScaler  # 이상치에 민감하고
ss = StandardScaler()
train_scaled =  ss.fit_transform(df.iloc[:,:-1])

ValueError: could not convert string to float: 'female'

In [ ]:
# 로지스틱회귀 import
from sklearn.linear_model import LogisticRegression
# 데이터를 잘 섞어야 함.
from sklearn.model_selection import train_test_split

In [ ]:
#훈련데이터와 테스트 (평가) 데이터 분리
x_train,x_test,y_train,y_test =  train_test_split(train_scaled,df.iloc[:,-1])

In [25]:
# 모델 생성
lr = LogisticRegression()

In [26]:
# 학습
lr.fit(x_train,y_train)

LogisticRegression()

In [27]:
# 평가 : accuracy 정확도측정
lr.score(x_test,y_test)

0.972027972027972

In [33]:
len(lr.coef_[0])

30

In [34]:
lr.intercept_

array([0.29833896])

In [36]:
#예측
y_predict = lr.predict(x_test)

In [38]:
# 정답은  y_test

In [41]:
conf = np.zeros((2,2))

In [55]:
y_test.values

array([1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0])

In [56]:
for i in range(len(y_predict)):
    row = y_predict[i]
    col = y_test.values[i]
    conf[row, col] += 1    

In [59]:
(conf[0,0] + conf[1,1]) / len(y_predict)

0.972027972027972

In [60]:
0.972027972027972

0.972027972027972

In [79]:
temp = x_test[0]+1.05
temp

array([ 0.69007116, -0.33917728,  0.67314948,  0.62313119,  2.26263912,
        0.74675768,  0.41221606,  0.66517582,  0.06928859,  1.32818923,
        0.38600621,  0.73275575,  0.43019236,  0.52708363,  0.67299174,
        0.75277167,  0.62314589,  0.77649227,  0.01813282,  0.78979944,
        0.58837373,  0.30137074,  0.61926066,  0.5558804 ,  2.02891709,
        0.85174678,  0.60340581,  1.06360918,  0.21076707,  1.13778878])

In [80]:
print(x_test.shape)
temp = temp.reshape(-1,30)

(143, 30)


In [81]:
lr.predict(temp)

array([0])

In [82]:
lr.predict(x_test[0].reshape(-1,30))

array([1])

In [83]:
# 기계학습 머신러닝
# 탐색적 데이터분석 
# 예측 , 분류(이진분류)

# 1. 모델선택 
# 2. 모델 객체 생성         - 모델명()
# 3. 학습데이터로 모델 훈련 - fit()
# 4. 평가데이터로 모델 평가 - score()
# 5. 예측                   - predict()

In [103]:
# 생존할수 있는지 예측
df = sns.load_dataset('titanic')
df.dropna(inplace=True)
X = df[['pclass', 'who', 'age']] 
Y = df['survived']

In [104]:

X['who'] = X['who'].map({'man':0,'woman':1,'child':2}).astype(np.int32)

C:\Users\user\AppData\Local\Temp\ipykernel_7760\3902911092.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['who'] = X['who'].map({'man':0,'woman':1,'child':2}).astype(np.int32)


In [105]:
X['who'].unique()

array([1, 0, 2])

In [106]:
X

pclass  who   age
1         1    1  38.0
3         1    1  35.0
6         1    0  54.0
10        3    2   4.0
11        1    1  58.0
..      ...  ...   ...
871       1    1  47.0
872       1    0  33.0
879       1    1  56.0
887       1    1  19.0
889       1    0  26.0

[182 rows x 3 columns]

In [107]:
X = ss.fit_transform(X)

In [152]:
x_train,x_test,y_train,y_test = train_test_split(X,Y,random_state=100,stratify=Y)

In [153]:
lr.fit(x_train,y_train)

LogisticRegression()

In [154]:
lr.score(x_test,y_test)

0.8695652173913043

In [1]:
# 정밀도 :   TP / (FP + TP)   Positive한 예측성능을 더 정밀하게 평가하기 위한 지표
# 예측이 positive한 것중에서 참인 비율
from sklearn.metrics import precision_score

In [2]:
#재현율
# 실제값이 positive한 것(FN+TP)중에서 참인 TP의 비율의미
# 실제 positive인 데이터를 정확히 예측했는지 평가하는 지표(민감도 , TPR)  -의료계통에서는 민감도
# TP / (FN + TP)
from sklearn.metrics import recall_score

In [3]:
# F1 스코어
# 정밀도와 재현율을 결합한 지표
# 정밀도 재현율이  서로 트레이드 오프(상충관계) 문제점을 고려해서 정확한 지표를 평가하기위해 
# 2 * (정밀도*재현율) / (정밀도 + 재현율)
from sklearn.metrics import f1_score

In [4]:
# FPR : 실제 Negative한 데이터를 Positive로  거짓으로 예측한 비율
# TPR : 실제 Positive한 데이터를 참 True로 예측한비율(재현율)
# ROC기반의 AUC 스코어
#    1에 가까울수록 좋은  성능을 의미
# ROC 기반 AUC 스코어
from sklearn.metrics import roc_auc_score