In [2]:
url = 'https://raw.githubusercontent.com/leekyuyoungSandeateak/20220823_start_sandeateak/main/II%20%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D/data2.csv?token=GHSAT0AAAAAABZZF54C25Q3JQFGSZXTNWXGY2HQB5A'

In [3]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv(url)
df = df.iloc[:,1:]
df.head()

Weight  Length  Diagonal  Height   Width type
0     5.9     8.4       8.8  2.1120  1.4080    A
1    32.0    13.7      14.7  3.5280  1.9992    A
2    40.0    15.0      16.0  3.8240  2.4320    A
3    51.5    16.2      17.2  4.5924  2.6316    A
4    70.0    17.4      18.5  4.5880  2.9415    A

In [6]:
# 다중분류 - logistic 회귀 - sigmoid  0, 1

In [7]:
# 시그모이드 VS 소프트 맥스

In [8]:
from sklearn.linear_model import LogisticRegression

In [49]:
lr = LogisticRegression(max_iter=50000, C=20)

In [50]:
# help(LogisticRegression)

In [51]:
# scaled 된 학습데이터를 가지고 학습
# scaled된 테스트 데이털르 가지고 분류
from sklearn.preprocessing import  StandardScaler

In [52]:
# 학습과, 정답을 분리
# 학습데이터를 스케일링
# 훈련데이터와 테스트 데이터 분리
# 학습
# 평가 및 예측

In [53]:
X = df.iloc[:,:-1]
Y = df.iloc[:,-1]

In [54]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
X = ss.fit_transform(X)

In [55]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test =  train_test_split(X,Y)

In [56]:
lr.fit(x_train,y_train)

LogisticRegression(C=20, max_iter=50000)

In [57]:
lr.score(x_train,y_train), lr.score(x_test,y_test)

(0.907563025210084, 0.9)

In [58]:
lr.predict(x_test[:10])

array(['B', 'F', 'E', 'A', 'A', 'A', 'E', 'B', 'D', 'F'], dtype=object)

In [60]:
proba = lr.predict_proba(x_test[:10])
np.round(proba,3)

array([[0.   , 0.999, 0.   , 0.   , 0.   , 0.   , 0.001],
       [0.001, 0.369, 0.044, 0.   , 0.   , 0.504, 0.082],
       [0.361, 0.   , 0.12 , 0.   , 0.411, 0.098, 0.01 ],
       [0.912, 0.002, 0.009, 0.   , 0.   , 0.   , 0.076],
       [0.744, 0.   , 0.093, 0.   , 0.104, 0.049, 0.01 ],
       [0.882, 0.   , 0.087, 0.006, 0.   , 0.001, 0.024],
       [0.044, 0.   , 0.001, 0.   , 0.953, 0.002, 0.   ],
       [0.   , 0.981, 0.001, 0.   , 0.   , 0.013, 0.005],
       [0.039, 0.   , 0.   , 0.961, 0.   , 0.   , 0.   ],
       [0.   , 0.124, 0.041, 0.   , 0.   , 0.798, 0.037]])

In [68]:
decision = lr.decision_function(x_test[:10])
np.round(decision,3)

array([[ -3.865,  15.371,  -1.027,  -2.545, -21.89 ,   5.614,   8.341],
       [ -2.151,   4.428,   2.304,  -4.22 ,  -8.024,   4.738,   2.923],
       [  3.48 ,  -7.632,   2.375,  -3.933,   3.609,   2.173,  -0.072],
       [  6.984,   0.878,   2.404,  -0.72 , -11.506,  -2.538,   4.498],
       [  4.365,  -7.085,   2.283,  -3.668,   2.399,   1.646,   0.06 ],
       [  4.98 ,  -2.961,   2.658,   0.059,  -3.812,  -2.291,   1.367],
       [  5.014, -11.362,   1.064,  -3.171,   8.09 ,   1.766,  -1.402],
       [ -5.254,   9.637,   2.096,  -3.366, -12.84 ,   5.288,   4.439],
       [ 11.054,   1.5  ,  -2.684,  14.258, -14.09 , -14.612,   4.574],
       [ -2.57 ,   3.378,   2.27 ,  -4.48 ,  -6.008,   5.242,   2.17 ]])

In [61]:
lr.classes_

array(['A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype=object)

In [62]:
df.shape

(159, 6)

In [67]:
np.round(lr.coef_,2), lr.intercept_

(array([[ 3.93,  6.58, -8.9 , -6.48,  4.2 ],
        [-1.28, -1.1 ,  2.25,  7.89, -0.98],
        [-3.46, -4.95,  5.06, -0.72,  2.91],
        [-0.01,  3.59,  3.98, -3.64, -1.86],
        [-1.63,  0.79,  0.99, -4.76, -4.17],
        [ 0.28, -2.3 , -3.32,  6.51, -2.2 ],
        [ 2.16, -2.61, -0.05,  1.2 ,  2.1 ]]),
 array([ 2.74893427,  0.1851716 ,  1.74846591, -0.46465791, -6.38984436,
        -0.40942554,  2.58135602]))

In [ ]:
# sigmoid  : 돌리면 돌리수록 0또는 1로 수렴 
# softmax : 다중분류의 각 라벨에대한 확률을 계산할때 사용--> 출력벡터의 합이 1인 확률 함수
# 벡터의 각 원소를 정규화 하기위해서 입력값을 모두 지수값으로 바꿘준다.
# argmax같은 함수를 사용해서 어느 분류인지 판다

In [69]:
from scipy.special import softmax

In [70]:
proba = softmax(decision,axis = 1)
np.round(proba,3)

array([[0.   , 0.999, 0.   , 0.   , 0.   , 0.   , 0.001],
       [0.001, 0.369, 0.044, 0.   , 0.   , 0.504, 0.082],
       [0.361, 0.   , 0.12 , 0.   , 0.411, 0.098, 0.01 ],
       [0.912, 0.002, 0.009, 0.   , 0.   , 0.   , 0.076],
       [0.744, 0.   , 0.093, 0.   , 0.104, 0.049, 0.01 ],
       [0.882, 0.   , 0.087, 0.006, 0.   , 0.001, 0.024],
       [0.044, 0.   , 0.001, 0.   , 0.953, 0.002, 0.   ],
       [0.   , 0.981, 0.001, 0.   , 0.   , 0.013, 0.005],
       [0.039, 0.   , 0.   , 0.961, 0.   , 0.   , 0.   ],
       [0.   , 0.124, 0.041, 0.   , 0.   , 0.798, 0.037]])

In [ ]:
# 분류 - kNei....  로지스틱  - 확률  분류에 잘맞다...(이진(sigmoid) , 다중(softmax))
# 회귀 - kNei(단점), 선형회귀 - 차수를 늘려서 좀더 다양하게 수렴 -> 과대적합 ->규제(L1, L2)